export const ActionTypes = {
   GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
   GET_PRODUCT_FAIL: 'GET_PRODUCT_FAIL',

   GET_SELECTED_PRODUCT : 'GET_SELECTED_PRODUCT',
   GET_SELECTED_PRODUCT_FAIL : 'GET_SELECTED_PRODUCT_FAIL',
   REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',

   LOGIN_REQUEST: 'LOGIN_REQUEST',
   LOGIN_SUCCESS: 'LOGIN_SUCCESS',
   LOGIN_FAILURE: 'LOGIN_FAILURE',

   LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
}