export const ActionTypes = {
   GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
   GET_PRODUCT_FAIL: 'GET_PRODUCT_FAIL',

   GET_SELECTED_PRODUCT : 'GET_SELECTED_PRODUCT',
   GET_SELECTED_PRODUCT_FAIL : 'GET_SELECTED_PRODUCT_FAIL',

   REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT'
}